export const FONTS = [
  { name: "Inter", category: "Sans-serif", weights: ["400", "600", "700"] },
  { name: "Roboto", category: "Sans-serif", weights: ["400", "500", "700"] },
  { name: "Open Sans", category: "Sans-serif", weights: ["400", "600", "700"] },
  { name: "Montserrat", category: "Sans-serif", weights: ["400", "600", "700", "900"] },
  { name: "Poppins", category: "Sans-serif", weights: ["400", "600", "700"] },
  { name: "Lato", category: "Sans-serif", weights: ["400", "700"] },
  { name: "Raleway", category: "Sans-serif", weights: ["400", "600", "700", "900"] },
  { name: "Nunito", category: "Sans-serif", weights: ["400", "600", "700"] },
  { name: "Source Sans Pro", category: "Sans-serif", weights: ["400", "600", "700"] },
  { name: "DM Sans", category: "Sans-serif", weights: ["400", "500", "700"] },
  { name: "Work Sans", category: "Sans-serif", weights: ["400", "600", "700"] },
  { name: "Manrope", category: "Sans-serif", weights: ["400", "600", "700", "800"] },
  { name: "Plus Jakarta Sans", category: "Sans-serif", weights: ["400", "600", "700", "800"] },
  { name: "Playfair Display", category: "Serif", weights: ["400", "600", "700"] },
  { name: "Merriweather", category: "Serif", weights: ["400", "700"] },
  { name: "Lora", category: "Serif", weights: ["400", "600", "700"] },
  { name: "Georgia", category: "Serif", weights: ["400", "700"] },
  { name: "Crimson Text", category: "Serif", weights: ["400", "600", "700"] },
  { name: "EB Garamond", category: "Serif", weights: ["400", "500", "700"] },
  { name: "Cormorant Garamond", category: "Serif", weights: ["400", "600", "700"] },
  { name: "Libre Baskerville", category: "Serif", weights: ["400", "700"] },
  { name: "Bebas Neue", category: "Display", weights: ["400"] },
  { name: "Oswald", category: "Display", weights: ["400", "500", "600", "700"] },
  { name: "Anton", category: "Display", weights: ["400"] },
  { name: "Abril Fatface", category: "Display", weights: ["400"] },
  { name: "Righteous", category: "Display", weights: ["400"] },
  { name: "Fredoka", category: "Display", weights: ["400", "600", "700"] },
  { name: "Pacifico", category: "Display", weights: ["400"] },
  { name: "Lobster", category: "Display", weights: ["400"] },
  { name: "Bangers", category: "Display", weights: ["400"] },
  { name: "Black Han Sans", category: "Display", weights: ["400"] },
  { name: "Archivo Black", category: "Display", weights: ["400"] },
  { name: "Alfa Slab One", category: "Display", weights: ["400"] },
  { name: "Roboto Mono", category: "Monospace", weights: ["400", "500", "700"] },
  { name: "Source Code Pro", category: "Monospace", weights: ["400", "600", "700"] },
  { name: "Courier New", category: "Monospace", weights: ["400", "700"] },
  { name: "Space Mono", category: "Monospace", weights: ["400", "700"] },
  { name: "IBM Plex Mono", category: "Monospace", weights: ["400", "500", "700"] },
  { name: "JetBrains Mono", category: "Monospace", weights: ["400", "600", "700"] },
  { name: "Dancing Script", category: "Handwriting", weights: ["400", "600", "700"] },
  { name: "Great Vibes", category: "Handwriting", weights: ["400"] },
  { name: "Satisfy", category: "Handwriting", weights: ["400"] },
  { name: "Caveat", category: "Handwriting", weights: ["400", "600", "700"] },
  { name: "Kalam", category: "Handwriting", weights: ["400", "700"] },
  { name: "Indie Flower", category: "Handwriting", weights: ["400"] },
  { name: "Sacramento", category: "Handwriting", weights: ["400"] },
  { name: "Shadows Into Light", category: "Handwriting", weights: ["400"] },
  { name: "Permanent Marker", category: "Handwriting", weights: ["400"] },
  { name: "Cinzel", category: "Serif", weights: ["400", "600", "700"] },
  { name: "Fira Sans", category: "Sans-serif", weights: ["400", "500", "700"] },
  { name: "Cabin", category: "Sans-serif", weights: ["400", "600", "700"] },
  { name: "Rubik", category: "Sans-serif", weights: ["400", "500", "700"] },
  { name: "Titillium Web", category: "Sans-serif", weights: ["400", "600", "700"] },
  { name: "PT Sans", category: "Sans-serif", weights: ["400", "700"] },
  { name: "Noto Sans", category: "Sans-serif", weights: ["400", "700"] },
];

export function buildGoogleFontsCssUrl(fontName, weights = ["400", "700"]) {
  const family = encodeURIComponent(fontName).replace(/%20/g, "+");
  const wght = weights.join(";");
  return `https://fonts.googleapis.com/css2?family=${family}:wght@${wght}&display=swap`;
}
