/** @type {import('tailwindcss').Config} */
const withAlpha = (cssVar, fallback) => `rgb(var(${cssVar}, ${fallback}) / <alpha-value>)`;

export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': withAlpha('--color-surface-dim', '216 206 255'),
        'primary-container': withAlpha('--color-primary-container', '147 150 255'),
        'primary-dim': withAlpha('--color-primary-dim', '57 57 199'),
        'tertiary': withAlpha('--color-tertiary', '0 101 118'),
        'secondary': withAlpha('--color-secondary', '176 13 106'),
        'on-surface': withAlpha('--color-on-surface', '48 41 80'),
        'outline': withAlpha('--color-outline', '121 113 157'),
        'outline-variant': withAlpha('--color-outline-variant', '176 167 214'),
        'surface-variant': withAlpha('--color-surface-variant', '225 216 255'),
        'secondary-fixed': withAlpha('--color-secondary-fixed', '255 193 214'),
        'on-error-container': withAlpha('--color-on-error-container', '81 0 23'),
        'tertiary-fixed-dim': withAlpha('--color-tertiary-fixed-dim', '64 206 237'),
        'error-dim': withAlpha('--color-error-dim', '167 1 56'),
        'on-error': withAlpha('--color-on-error', '255 239 239'),
        'surface-container-high': withAlpha('--color-surface-container-high', '230 222 255'),
        'on-tertiary': withAlpha('--color-on-tertiary', '222 247 255'),
        'on-surface-variant': withAlpha('--color-on-surface-variant', '94 86 128'),
        'secondary-fixed-dim': withAlpha('--color-secondary-fixed-dim', '255 172 203'),
        'inverse-on-surface': withAlpha('--color-inverse-on-surface', '160 151 197'),
        'tertiary-fixed': withAlpha('--color-tertiary-fixed', '83 221 252'),
        'on-secondary-container': withAlpha('--color-on-secondary-container', '142 0 84'),
        'on-primary-container': withAlpha('--color-on-primary-container', '10 0 129'),
        'surface-container-lowest': withAlpha('--color-surface-container-lowest', '255 255 255'),
        'on-tertiary-fixed-variant': withAlpha('--color-on-tertiary-fixed-variant', '0 85 100'),
        'on-secondary-fixed-variant': withAlpha('--color-on-secondary-fixed-variant', '158 0 94'),
        'on-primary-fixed-variant': withAlpha('--color-on-primary-fixed-variant', '14 0 157'),
        'on-tertiary-container': withAlpha('--color-on-tertiary-container', '0 75 88'),
        'surface': withAlpha('--color-surface', '250 244 255'),
        'on-primary-fixed': withAlpha('--color-on-primary-fixed', '0 0 0'),
        'primary-fixed': withAlpha('--color-primary-fixed', '147 150 255'),
        'error-container': withAlpha('--color-error-container', '247 75 109'),
        'on-tertiary-fixed': withAlpha('--color-on-tertiary-fixed', '0 54 64'),
        'inverse-primary': withAlpha('--color-inverse-primary', '128 131 255'),
        'tertiary-container': withAlpha('--color-tertiary-container', '83 221 252'),
        'on-primary': withAlpha('--color-on-primary', '244 241 255'),
        'on-secondary-fixed': withAlpha('--color-on-secondary-fixed', '107 0 62'),
        'background': withAlpha('--color-background', '250 244 255'),
        'error': withAlpha('--color-error', '180 19 64'),
        'tertiary-dim': withAlpha('--color-tertiary-dim', '0 88 103'),
        'surface-container': withAlpha('--color-surface-container', '236 228 255'),
        'inverse-surface': withAlpha('--color-inverse-surface', '15 7 46'),
        'on-background': withAlpha('--color-on-background', '48 41 80'),
        'surface-bright': withAlpha('--color-surface-bright', '250 244 255'),
        'surface-container-low': withAlpha('--color-surface-container-low', '244 238 255'),
        'surface-tint': withAlpha('--color-surface-tint', '70 71 211'),
        'primary': withAlpha('--color-primary', '70 71 211'),
        'surface-container-highest': withAlpha('--color-surface-container-highest', '225 216 255'),
        'primary-fixed-dim': withAlpha('--color-primary-fixed-dim', '131 135 255'),
        'on-secondary': withAlpha('--color-on-secondary', '255 239 242'),
        'secondary-container': withAlpha('--color-secondary-container', '255 193 214'),
        'secondary-dim': withAlpha('--color-secondary-dim', '157 0 93'),
        'warn': withAlpha('--color-warn', '125 102 8'),
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'system-ui'],
        body: ['Manrope', 'system-ui'],
        label: ['Manrope', 'system-ui'],
      },
      boxShadow: {
        'nav': '0px 24px 48px rgba(48,41,80,0.06)',
        'card': '0px 24px 48px rgba(48,41,80,0.06)',
        'card-sm': '0px 12px 24px rgba(48,41,80,0.04)',
      },
    },
  },
  plugins: [],
};
